# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/177dQdP757mcObZSgPG5iNpopfzgJ4f6G
"""

# Utilizei o comando de import para pegar a bibliotéca para graficos
# Não esquecer de utilizar sempre o \n quando eu quiser fazer uma quebra de linha.
import matplotlib.pyplot as plt

# O primeiro passo é definir a classe 'Livro'
class Livro:
    def __init__(self, titulo, autor, genero, quantidade):
        self.titulo = titulo
        self.autor = autor
        self.genero = genero
        self.quantidade = quantidade

# O segundo passo é criar uma lista de livros
biblioteca = []  # Estou deixando a lista vazia, aqui serão salvos os livros

# O terceiro passo então, é uma função para cadastrar um novo livro
def cadastrar_livro():
    titulo = input("Digite o título do livro: ")
    autor = input("Digite o autor do livro: ")
    genero = input("Digite o gênero do livro: ")

    while True:
        try:
            quantidade = int(input("Digite a quantidade disponível: "))
            if quantidade < 0:
                print("Erro: A quantidade não pode ser negativa.")
            else:
                break
        except ValueError:
            print("Erro: Entrada inválida. Digite um número inteiro.")

    novo_livro = Livro(titulo, autor, genero, quantidade)
    biblioteca.append(novo_livro)
    print(f"Livro '{titulo}' foi cadastrado com sucesso!\n")

# Aqui eu vou deixar uma função que vai servir para listar todos os livros
def listar_livros():
    if len(biblioteca) == 0:
        print("Erro: Nenhum livro cadastrado na biblioteca.\n")
    else:
        print("\n===== LISTA DE LIVROS =====")
        for livro in biblioteca:
            print(f"Título: {livro.titulo}, Autor: {livro.autor}, Gênero: {livro.genero}, Quantidade: {livro.quantidade}")
        print("===========================\n")

# Aqui eu vou deixar uma função para buscar um livro pelo título
def buscar_livro():
    pesquisa = input("Digite o título do livro que deseja buscar: ").lower()
    encontrados = [livro for livro in biblioteca if pesquisa in livro.titulo.lower()]

    if len(encontrados) == 0:
        print("Erro: Nenhum livro encontrado com esse título.\n")
    else:
        print("\n===== LIVROS ENCONTRADOS =====")
        for livro in encontrados:
            print(f"Título: {livro.titulo}, Autor: {livro.autor}, Gênero: {livro.genero}, Quantidade: {livro.quantidade}")
        print("==============================\n")

# Aqui eu vou deixar a função para gerar gráfico de quantidade de livros por gênero
def gerar_grafico():
    if len(biblioteca) == 0:
        print("Erro: Nenhum livro cadastrado para gerar gráfico.\n")
        return

    # Nessa parte vou deixar algumas linhas que vão criar um dicionário para contar quantidade por gênero
    genero_quantidade = {}
    for livro in biblioteca:
        if livro.genero in genero_quantidade:
            genero_quantidade[livro.genero] += livro.quantidade
        else:
            genero_quantidade[livro.genero] = livro.quantidade

    # O que vai fazer necessariamente um gráfico ser criado.
    plt.figure(figsize=(8,5))
    plt.bar(genero_quantidade.keys(), genero_quantidade.values(), color='skyblue')
    plt.title("Quantidade de Livros por Gênero")
    plt.xlabel("Gênero")
    plt.ylabel("Quantidade")
    plt.show()

# Código do programa em si:
def main():
    while True:
        print("===== BIBLIOTECA DO ALBUQUERQUE =====")
        print("1. Cadastrar Livro")
        print("2. Listar Livros")
        print("3. Buscar Livro por Título")
        print("4. Gerar Gráfico de Livros por Gênero")
        print("5. Sair")

        escolha = input("Escolha uma opção: ")

        if escolha == '1':
            cadastrar_livro()
        elif escolha == '2':
            listar_livros()
        elif escolha == '3':
            buscar_livro()
        elif escolha == '4':
            gerar_grafico()
        elif escolha == '5':
            print("Saindo do sistema...")
            break
        else:
            print("Erro: Opção inválida. Tente novamente.\n")


main()